version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "/calendar/cmd/server/http_server.go"]
    ports:
      - "7777:7777"
    depends_on:
      - postgres
  postgres:
    image: postgres:10.10
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: events