version: "3"

networks:
  rabbit:
    driver: bridge
  db:
    driver: bridge

services:
  integration_tests:
    build: ./integration_tests
    command: "true"
    links:
      - api
      - scheduler
    environment:
      TESTS_AMQP_DSN: "amqp://guest:guest@rabbit:5672/"
    networks:
      - db
      - rabbit

  api:
    build: ./api
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "7766:7766"
    environment:
      API_MIC_DB_DSN: "postgres://calendar:123123@postgres:5432/calendar?sslmode=disable"
      API_MIC_SERVER_ADDR: ":7766"
    networks:
      - db
      - rabbit

  scheduler:
    build: ./scheduler
    command: ./scheduler --config=./config/development/config.toml
    depends_on:
      - postgres
      - rabbit
    restart: on-failure
    environment:
      SCHEDULER_MIC_DB_DSN: "postgres://calendar:123123@postgres:5432/calendar?sslmode=disable"
      SCHEDULER_MIC_AMQP_DSN: "amqp://guest:guest@rabbit:5672/"
    networks:
      - db
      - rabbit

  postgres:
    image: postgres:11.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: calendar
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - db

  rabbit:
    image: rabbitmq:3.7.17-management
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
    volumes:
      - ./rabbit.def.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbit.config:/etc/rabbitmq/rabbitmq.config:ro
    networks:
      - rabbit