version: "3"

networks:
  rabbit:
    driver: bridge
  db:
    driver: bridge

services:
  api:
    build: ./api
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "7777:7777"
    expose:
      - 7777
    environment:
      API_MIC_DB_DSN: "postgres://calendar:123123@postgres:5432/calendar?sslmode=disable"
      API_MIC_SERVER_ADDR: ":7777"
    networks:
      - db

  scheduler:
    build: ./scheduler
    depends_on:
      - postgres
      - rabbit
    restart: on-failure
    environment:
      SCHEDULER_MIC_DB_DSN: "postgres://calendar:123123@postgres:5432/calendar?sslmode=disable"
      SCHEDULER_MIC_AMQP_DSN: "amqp://guest:guest@rabbit:5672/"
    networks:
      - db
      - rabbit

  notifier:
    build: ./notifier
    depends_on:
      - rabbit
      - scheduler
    restart: on-failure
    environment:
      NOTIFIER_MIC_AMQP_DSN: "amqp://guest:guest@rabbit:5672/"
    networks:
      - rabbit

  postgres:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: calendar
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - db

  rabbit:
    image: rabbitmq:3.7.17-management
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
    volumes:
      - ./rabbit.def.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbit.config:/etc/rabbitmq/rabbitmq.config:ro
    networks:
      - rabbit