---
global:
  scrape_interval: '5s'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'api'
    static_configs:
      - targets:
          - 'api:9102'

  - job_name: 'scheduler'
    static_configs:
      - targets:
          - 'scheduler:9878'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets:
          - 'postgres-exporter:9187'
