Interval = 3600 #one hour

[Postgres]
DSN = "postgres://calendar:123123@localhost:5432/calendar?sslmode=disable"
PingTimeout = 430
MaxOpenConns = 10
MaxIdleConns = 5
ConnMaxLifetime = 15

[RabbitMQ]
URL = "amqp://guest:guest@localhost:5672/"
