Interval = 5 #second

[Postgres]
DSN = "postgres://calendar:123123@postgres:5432/calendar?sslmode=disable"
PingTimeout = 430
MaxOpenConns = 10
MaxIdleConns = 5
ConnMaxLifetime = 15

[RabbitMQ]
URL = "amqp://guest:guest@rabbit:5672/"

[Prometheus]
Port = 9878
